# Generated by Django 2.0.6 on 2019-03-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20190228_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
